services:
  sqlite-db:
    image: keinos/sqlite3:latest
    container_name: reimbursement-sqlite-db
    command: sh -c "mkdir -p /data && touch /data/dev.db && tail -f /dev/null"
    volumes:
      - sqlite_data:/data
      - ./database:/workspace-db

volumes:
  sqlite_data:
